package com.phimnguonc

import com.fasterxml.jackson.annotation.JsonProperty
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.plugins.CloudstreamPlugin
import com.lagradost.cloudstream3.plugins.Plugin
import com.lagradost.cloudstream3.utils.*
import com.lagradost.cloudstream3.network.WebViewResolver
import java.net.URLEncoder
import java.util.EnumSet

// ═══════════════════════════════════════════════════════════════
//  NguonC Plugin – Rebuilt from real DevTools data (2026-06-28)
//
//  Findings from live DevTools capture:
//  • m3u9 (NOT m3u8) is plaintext HLS, NOT AES-GCM encrypted
//  • URL: embedXX.streamc.xyz/{base64_token}.m3u9?xat={auth_hex}
//  • Segments: malaysXX.hlhlhoho2.top/{hash}/streamaaa0000.png
//  • ?xat= token is generated by JS with session cookie
//  • Segments use .png extension (not .ts!)
//  • Without valid xat → "Unauthorized"
//  • WebView with session cookie → gets valid xat → plaintext m3u9
// ═══════════════════════════════════════════════════════════════

@CloudstreamPlugin
class PhimNguonCPlugin : Plugin() {
    override fun load() {
        registerMainAPI(PhimNguonCProvider())
    }
}

class PhimNguonCProvider : MainAPI() {
    override var mainUrl = "https://phim.nguonc.com"
    override var name = "NguonC"
    override val hasMainPage = true
    override var lang = "vi"
    override val hasDownloadSupport = true
    override val supportedTypes = setOf(TvType.Movie, TvType.TvSeries, TvType.Anime)

    companion object {
        private const val UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
    }

    private val apiHeaders = mapOf(
        "User-Agent" to UA,
        "Accept" to "application/json, text/plain, */*",
        "Accept-Language" to "vi-VN,vi;q=0.9,en;q=0.8",
        "Referer" to "$mainUrl/"
    )

    // ═══════════════════════════════════════════════════════════
    //  MainPage – 100% API, matching confirmed working paths
    //  JSON confirmed: {"status":"success","paginate":{...},"items":[...]}
    // ═══════════════════════════════════════════════════════════

    override val mainPage = mainPageOf(
        "api/films/phim-moi-cap-nhat" to "Phim Mới Cập Nhật",
        "api/films/phim-le"           to "Phim Lẻ",
        "api/films/phim-bo"           to "Phim Bộ",
        "api/films/tv-shows"          to "TV Shows",
        "api/films/hoat-hinh"         to "Hoạt Hình",
        "api/films/phim-18"           to "18+"
    )

    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
        val url = "$mainUrl/${request.data}?page=$page"
        val res = app.get(url, headers = apiHeaders, timeout = 20)
            .parsedSafe<NguonCApiResponse>()
        val items = res?.items?.mapNotNull { parseApiItem(it) } ?: emptyList()
        return newHomePageResponse(request.name, items, hasNext = items.isNotEmpty())
    }

    // ═══════════════════════════════════════════════════════════
    //  Search
    // ═══════════════════════════════════════════════════════════

    override suspend fun search(query: String): List<SearchResponse> {
        val encoded = URLEncoder.encode(query, "utf-8")

        // Try search endpoint
        for (path in listOf("api/films/search?keyword=$encoded", "api/films?keyword=$encoded")) {
            try {
                val res = app.get("$mainUrl/$path", headers = apiHeaders, timeout = 15)
                    .parsedSafe<NguonCApiResponse>()
                if (!res?.items.isNullOrEmpty()) {
                    return res!!.items!!.mapNotNull { parseApiItem(it) }
                }
            } catch (_: Exception) {}
        }
        return emptyList()
    }

    // ═══════════════════════════════════════════════════════════
    //  Load – Film detail
    //  Confirmed JSON structure:
    //  {"status":"success","movie":{"episodes":[{"server_name":"Vietsub #1",
    //   "items":[{"name":"1","slug":"tap-1",
    //   "embed":"https://embed13.streamc.xyz/embed.php?hash=..."}]}]}}
    // ═══════════════════════════════════════════════════════════

    override suspend fun load(url: String): LoadResponse {
        val slug = url.trim().trimEnd('/').substringAfterLast("/")
        val res = app.get("$mainUrl/api/film/$slug", headers = apiHeaders, timeout = 20)
            .parsedSafe<NguonCDetailResponse>()
        val movie = res?.movie
            ?: throw ErrorLoadingException("Không thể tải dữ liệu phim")

        // Build episode list
        val epMap = linkedMapOf<String, MutableList<String>>()
        movie.episodes?.forEachIndexed { idx, server ->
            val serverName = server.server_name ?: server.name
                ?: if (idx == 0) "Vietsub" else "Thuyết minh"
            val items = server.items ?: server.list ?: emptyList()
            items.forEach { ep ->
                val embed = ep.embed?.replace("\\/", "/")?.trim() ?: ""
                val m3u8 = ep.m3u8?.replace("\\/", "/")?.trim() ?: ""
                val epName = ep.name ?: "0"
                if (embed.isNotBlank())
                    epMap.getOrPut(epName) { mutableListOf() }.add("$serverName::$embed")
                if (m3u8.isNotBlank() && m3u8 != embed)
                    epMap.getOrPut(epName) { mutableListOf() }.add("$serverName::$m3u8")
            }
        }
        if (epMap.isEmpty()) throw ErrorLoadingException("Không tìm thấy tập phim")

        val episodes = epMap.map { (epName, embeds) ->
            newEpisode(embeds.distinct().joinToString("|")) {
                this.name = "Tập $epName"
                this.episode = epName.toIntOrNull()
            }
        }.sortedBy { it.episode ?: 0 }

        // Metadata
        val categories = movie.category ?: emptyMap()
        val theLoai = categories.values
            .find { it.group?.name == "Thể loại" }
            ?.list?.mapNotNull { it.name } ?: emptyList()
        val quocGia = categories.values
            .find { it.group?.name == "Quốc gia" }
            ?.list?.mapNotNull { it.name }?.joinToString(", ") ?: ""
        val nam = categories.values
            .find { it.group?.name == "Năm" }
            ?.list?.firstOrNull()?.name ?: ""

        val plot = buildString {
            val orig = movie.original_name ?: ""
            if (orig.isNotBlank() && orig != (movie.name ?: ""))
                append("<i>$orig</i><br><br>")
            fun info(l: String, v: String?) { if (!v.isNullOrBlank()) append("<b>$l:</b> $v<br>") }
            info("📺 Trạng thái", movie.current_episode)
            if ((movie.total_episodes ?: 0) > 0) info("🎬 Số tập", "${movie.total_episodes} tập")
            info("⏱ Thời lượng", movie.time)
            info("🎥 Chất lượng", movie.quality)
            info("🔊 Ngôn ngữ", movie.language)
            info("🌍 Quốc gia", quocGia)
            info("🎬 Đạo diễn", movie.director)
            info("🎭 Diễn viên", movie.casts)
            val desc = movie.description ?: ""
            if (desc.isNotBlank()) { append("<br><b>📖 NỘI DUNG</b><br>"); append(desc) }
        }

        return newTvSeriesLoadResponse(movie.name ?: "", url, TvType.TvSeries, episodes) {
            this.posterUrl = movie.poster_url ?: movie.thumb_url
            this.plot = plot
            this.tags = theLoai
            this.year = nam.toIntOrNull()
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  LoadLinks – WebView captures the REAL m3u9 URL
    //
    //  How streamc.xyz works (from DevTools):
    //  1. Browser loads embed.php?hash=XXX
    //  2. Cloudflare sets session cookie
    //  3. JS (player.js) reads data-obf → extracts sUb token
    //  4. JS generates xat auth token from session
    //  5. JW Player fetches: /{sUb_token}.m3u9?xat={auth}
    //  6. Server returns PLAINTEXT m3u9 with .png segments
    //
    //  Strategy: WebView loads embed page → JS runs → intercept
    //  the m3u9 request OR the .png segment requests
    // ═══════════════════════════════════════════════════════════

    override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        val entries = data.split("|").mapNotNull { entry ->
            val parts = entry.trim().split("::", limit = 2)
            when {
                parts.size == 2 -> Pair(parts[0], parts[1])
                parts.size == 1 && parts[0].startsWith("http") -> Pair("Vietsub", parts[0])
                else -> null
            }
        }

        for ((serverName, embedUrl) in entries) {
            try {
                if (resolveEmbed(serverName, embedUrl, callback)) return true
            } catch (e: Exception) {
                println("[NguonC] Error: ${e.message}")
            }
        }
        return false
    }

    private suspend fun resolveEmbed(
        serverName: String,
        rawUrl: String,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        var embedUrl = rawUrl

        // Fix legacy phimmoi.net links
        if (rawUrl.contains("sing.phimmoi.net")) {
            val hash = Regex("""/([^/]+)/hls\.m3u8""").find(rawUrl)?.groupValues?.get(1) ?: return false
            embedUrl = "https://embed15.streamc.xyz/embed.php?hash=$hash"
        }

        println("[NguonC] === Resolving: $embedUrl ===")

        // ═══════════════════════════════════════════════════════════
        // APPROACH: Proxy server serves continuous MPEG-TS stream
        //
        // PROVEN FACTS from 7 rounds of testing:
        //   ✅ ExtractorLinkType.VIDEO + single segment = plays 8s
        //   ✅ CDN segments work with Referer: embedXX.streamc.xyz
        //   ✅ Proxy server on 127.0.0.1 = CronetDataSource accepts
        //   ❌ M3U8 type always fails (MALFORMED — .png extension issue)
        //
        // NEW APPROACH: Proxy concatenates ALL segments into one stream
        //   ExoPlayer sees: http://127.0.0.1:PORT/video.ts (type VIDEO)
        //   Proxy internally: fetches seg0, seg1, seg2... streams bytes
        //   Result: full continuous video, no HLS parsing needed
        // ═══════════════════════════════════════════════════════════
        try {
            // Step 1: WebView intercept m3u8 to get segment URLs
            val interceptor = WebViewResolver(
                Regex("""streamc\.xyz/[A-Za-z0-9+/=_-]+\.m3u8""")
            )
            val resp = app.get(
                embedUrl,
                interceptor = interceptor,
                headers = mapOf("Referer" to "$mainUrl/", "User-Agent" to UA),
                timeout = 30
            )
            val m3u8Content = resp.text
            val embedDomain = Regex("""https?://[^/]+""").find(embedUrl)?.value ?: ""

            // Extract segment URLs from m3u8
            val segments = m3u8Content.lines()
                .map { it.trim() }
                .filter { it.startsWith("https://") }

            if (segments.isEmpty()) {
                println("[NguonC] No segments in m3u8, trying fallback")
                return resolveViaSegment(serverName, embedUrl, callback)
            }

            println("[NguonC] Got ${segments.size} segments from m3u8")

            // Step 2: Start proxy that streams segments as continuous video
            val serverSocket = java.net.ServerSocket(0)
            val port = serverSocket.localPort
            val proxyUrl = "http://127.0.0.1:$port/video.ts"

            Thread {
                try {
                    serverSocket.soTimeout = 600_000
                    while (!serverSocket.isClosed) {
                        try {
                            val client = serverSocket.accept()
                            Thread {
                                streamSegments(client, segments, embedDomain)
                            }.apply { isDaemon = true }.start()
                        } catch (_: java.net.SocketTimeoutException) { break }
                          catch (_: java.net.SocketException) { break }
                    }
                } catch (_: Exception) {}
                try { serverSocket.close() } catch (_: Exception) {}
            }.apply { isDaemon = true }.start()

            println("[NguonC] ✓ Streaming proxy at $proxyUrl")

            // Use VIDEO type — ExoPlayer treats it as a regular video file
            callback(newExtractorLink("NguonC", serverName, proxyUrl, ExtractorLinkType.VIDEO) {
                this.referer = ""
                this.quality = Qualities.P1080.value
                this.headers = mapOf("User-Agent" to UA)
            })
            return true

        } catch (e: Exception) {
            println("[NguonC] Proxy approach failed: ${e.message}")
        }

        // Fallback: direct segment (plays 8s at least)
        return resolveViaSegment(serverName, embedUrl, callback)

        println("[NguonC] ✗ All strategies failed for: $embedUrl")
        return false
    }

    /**
     * Stream all segments concatenated as one continuous MPEG-TS stream.
     * ExoPlayer sees this as a regular video file (no HLS parsing).
     * Each .png segment is actually MPEG-TS data despite the extension.
     */
    private fun streamSegments(
        client: java.net.Socket,
        segments: List<String>,
        segReferer: String
    ) {
        try {
            val input = client.getInputStream().bufferedReader()
            val output = client.getOutputStream()
            // Read HTTP request
            input.readLine() ?: return
            while (input.readLine()?.isNotBlank() == true) { /* skip headers */ }

            // Send HTTP response header (chunked transfer — unknown total size)
            val crlf = "\r\n"
            output.write(("HTTP/1.1 200 OK${crlf}Content-Type: video/mp2t${crlf}Transfer-Encoding: chunked${crlf}Access-Control-Allow-Origin: *${crlf}Connection: close${crlf}${crlf}").toByteArray())
            output.flush()

            // Stream each segment sequentially
            for ((idx, segUrl) in segments.withIndex()) {
                try {
                    val conn = java.net.URL(segUrl).openConnection() as java.net.HttpURLConnection
                    conn.connectTimeout = 15000
                    conn.readTimeout = 30000
                    conn.setRequestProperty("User-Agent", UA)
                    conn.setRequestProperty("Referer", "$segReferer/")
                    conn.setRequestProperty("Origin", segReferer)
                    conn.connect()

                    if (conn.responseCode == 200) {
                        val bytes = conn.inputStream.readBytes()
                        conn.disconnect()
                        // Send chunk: size in hex + CRLF + data + CRLF
                        output.write("${Integer.toHexString(bytes.size)}${crlf}".toByteArray())
                        output.write(bytes)
                        output.write(crlf.toByteArray())
                        output.flush()
                    } else {
                        conn.disconnect()
                        break // Stop on error (likely end of video)
                    }
                } catch (_: Exception) {
                    break // Connection closed by player or network error
                }
            }

            // Send final empty chunk to signal end
            try {
                output.write("0${crlf}${crlf}".toByteArray())
                output.flush()
            } catch (_: Exception) {}
            client.close()
        } catch (_: Exception) {
            try { client.close() } catch (_: Exception) {}
        }
    }

    /** Fallback: intercept single segment URL (plays ~8s, proven working) */
    private suspend fun resolveViaSegment(
        serverName: String,
        embedUrl: String,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        try {
            val interceptor = WebViewResolver(Regex("""streamaaa\d+\.png"""))
            val resp = app.get(
                embedUrl,
                interceptor = interceptor,
                headers = mapOf("Referer" to "$mainUrl/", "User-Agent" to UA),
                timeout = 30
            )
            val capturedUrl = resp.url ?: ""
            if (capturedUrl.contains("streamaaa")) {
                println("[NguonC] ✓ Fallback segment: ${capturedUrl.take(100)}")
                val embedDomain = Regex("""https?://[^/]+""").find(embedUrl)?.value ?: ""
                callback(newExtractorLink("NguonC", serverName, capturedUrl, ExtractorLinkType.VIDEO) {
                    this.referer = "$embedDomain/"
                    this.quality = Qualities.P1080.value
                    this.headers = mapOf("User-Agent" to UA, "Origin" to embedDomain)
                })
                return true
            }
        } catch (e: Exception) {
            println("[NguonC] Fallback segment failed: ${e.message}")
        }
        return false
    }

    // ═══════════════════════════════════════════════════════════
    //  parseApiItem – confirmed JSON structure
    // ═══════════════════════════════════════════════════════════

    private fun parseApiItem(item: NguonCApiItem): SearchResponse? {
        val slug = item.slug ?: return null
        val title = item.name ?: return null
        val href = "$mainUrl/phim/$slug"
        val poster = item.poster_url ?: item.thumb_url
        val currentEp = item.current_episode ?: ""

        val epCount: Int? = when {
            currentEp.equals("FULL", true) -> null
            currentEp.startsWith("Hoàn tất", true) -> null
            else -> Regex("""[Tt]ập\s*(\d+)""").find(currentEp)?.groupValues?.get(1)?.toIntOrNull()
                ?: Regex("""(\d+)\s*/\s*\d+""").find(currentEp)?.groupValues?.get(1)?.toIntOrNull()
        }

        val lang = item.language ?: ""
        val hasSub = lang.contains("Vietsub", true)
        val hasDub = lang.contains("Thuyết Minh", true)
        val dubStatus = when {
            hasSub && hasDub -> EnumSet.of(DubStatus.Subbed, DubStatus.Dubbed)
            hasDub -> EnumSet.of(DubStatus.Dubbed)
            else -> EnumSet.of(DubStatus.Subbed)
        }
        val quality = when (item.quality?.uppercase()) {
            "FHD", "HD" -> SearchQuality.HD
            "CAM" -> SearchQuality.Cam
            "SD" -> SearchQuality.SD
            else -> SearchQuality.HD
        }

        return newAnimeSearchResponse(title, href, TvType.TvSeries) {
            this.posterUrl = poster
            this.quality = quality
            this.dubStatus = dubStatus
            if (epCount != null) {
                if (hasSub) addSub(epCount)
                if (hasDub) addDub(epCount)
                if (!hasSub && !hasDub) addSub(epCount)
            }
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  Data classes – matching confirmed JSON
    // ═══════════════════════════════════════════════════════════

    data class NguonCApiResponse(
        @JsonProperty("status") val status: String? = null,
        @JsonProperty("items") val items: List<NguonCApiItem>? = null
    )
    data class NguonCApiItem(
        @JsonProperty("slug") val slug: String? = null,
        @JsonProperty("name") val name: String? = null,
        @JsonProperty("poster_url") val poster_url: String? = null,
        @JsonProperty("thumb_url") val thumb_url: String? = null,
        @JsonProperty("current_episode") val current_episode: String? = null,
        @JsonProperty("quality") val quality: String? = null,
        @JsonProperty("language") val language: String? = null
    )
    data class NguonCDetailResponse(
        @JsonProperty("status") val status: String? = null,
        @JsonProperty("movie") val movie: NguonCMovie? = null
    )
    data class NguonCMovie(
        @JsonProperty("name") val name: String? = null,
        @JsonProperty("original_name") val original_name: String? = null,
        @JsonProperty("slug") val slug: String? = null,
        @JsonProperty("poster_url") val poster_url: String? = null,
        @JsonProperty("thumb_url") val thumb_url: String? = null,
        @JsonProperty("description") val description: String? = null,
        @JsonProperty("quality") val quality: String? = null,
        @JsonProperty("language") val language: String? = null,
        @JsonProperty("director") val director: String? = null,
        @JsonProperty("casts") val casts: String? = null,
        @JsonProperty("time") val time: String? = null,
        @JsonProperty("current_episode") val current_episode: String? = null,
        @JsonProperty("total_episodes") val total_episodes: Int? = null,
        @JsonProperty("category") val category: Map<String, NguonCCategory>? = null,
        @JsonProperty("episodes") val episodes: List<NguonCServer>? = null
    )
    data class NguonCCategory(
        @JsonProperty("group") val group: NguonCGroup? = null,
        @JsonProperty("list") val list: List<NguonCGroupItem>? = null
    )
    data class NguonCGroup(@JsonProperty("name") val name: String? = null)
    data class NguonCGroupItem(
        @JsonProperty("id") val id: String? = null,
        @JsonProperty("name") val name: String? = null
    )
    data class NguonCServer(
        @JsonProperty("server_name") val server_name: String? = null,
        @JsonProperty("name") val name: String? = null,
        @JsonProperty("items") val items: List<NguonCEpisode>? = null,
        @JsonProperty("list") val list: List<NguonCEpisode>? = null
    )
    data class NguonCEpisode(
        @JsonProperty("name") val name: String? = null,
        @JsonProperty("slug") val slug: String? = null,
        @JsonProperty("embed") val embed: String? = null,
        @JsonProperty("m3u8") val m3u8: String? = null
    )
}
